### ISSUE TITLE
Problemas com a versão e libs do JasperReports

### ISSUE THREAD

**Issue by tomazcunha** [wellinsongabriel/cadastro-clientes#1]
Olá, obrigado pelo tutorial, mas estou tendo alguns problemas para compilar o 'Coffee.jrxml' . 

A questão é que não dá mais para usar o plugin do Eclipse para gerar o 'Coffee.jrxml', tive que baixar e fazer pelo 'Jaspersoft-Studio', então essas dependências do Jasper acredito que preciso incluir manualmente agora. 

Como não tem o arquivo '.pom' do Maven para as dependências, tive que incluir os '.jar' do Jarper no diretório lib e incluir na PATH. 
Busquei a versão mais nova dos jar em "https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports", e outros arquivos de dependência em "https://jar-download.com/artifacts/net.sf.jasperreports/jasperreports/6.21.3", mas na hora de rodar, tive alguns erros.
O erro atual que estou tendo é "Exception in thread “AWT-EventQueue-0” java.lang.NoClassDefFoundError: org/springframework/core/io/Resource".

Saber me dizer qual são as libs e versões que você usou no projeto?

**Comment by wellinsongabriel** [comment]
Oi tudo bom? Tente adicionar esse conjunto de libs ao **classpath** do seu projeto, aqui funcionou bem!

[jasperreports](https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports/6.16.0)
[commons-beanutils](https://mvnrepository.com/artifact/commons-beanutils/commons-beanutils/1.9.4)
[commons-collections4](https://mvnrepository.com/artifact/org.apache.commons/commons-collections4/4.4)
[commons-digester](https://mvnrepository.com/artifact/commons-digester/commons-digester/2.1)
[commons-logging](https://mvnrepository.com/artifact/commons-logging/commons-logging/1.1.1)

Foi utilizado a versão 6.21.2 do Jaspersoft Studio community, link oficial [aqui](https://community.jaspersoft.com/download-jaspersoft/community-edition/jaspersoft-studio_6.21.2)
